import { listByKind, getEntity, incomingLinks, outgoingLinks } from "@sandlabs/data";
// Generated by packages/datamine/scripts/build_container_loot.py — blueprint id -> the
// wiki container slug and the exact roll pool ("group") that blueprint uses.
import CONTAINER_BLUEPRINTS from "./containerBlueprints.json";

/** Kinds that have a wiki detail route, in collision-priority order. */
const KIND_ROUTE: { kind: string; base: string }[] = [
  { kind: "item", base: "/items" },
  { kind: "environment", base: "/environment" },
  { kind: "trampler-part", base: "/tramplers" },
];

/** Curated aliases for loot labels whose in-game name diverges from the wiki entity
 *  name, so plain name-matching can't connect them. Keyed by (un-normalized) label →
 *  wiki slug; each is verified against the store when the index is built, so a stale
 *  entry degrades to plain text rather than a dead link. Extend as mismatches surface.
 *
 *  Turrets: the map spawns the "packable" walker part (walker_…Turret…_packable) while
 *  the wiki models the lootable as the packed artillery "Kit" item
 *  (game-packed-…-turret-t{N}-container). Armored / rail-gun / untiered turrets are
 *  intentionally omitted — they have no corresponding wiki kit item. */
const ALIASES: Record<string, string> = {
  "Auto Mounted Turret T1 Packable": "game-packed-auto-turret-t1-container",
  "Auto Mounted Turret T2 Packable": "game-packed-auto-turret-t2-container",
  "Auto Mounted Turret T3 Packable": "game-packed-auto-turret-t3-container",
  "Auto Mounted Turret T4 Accelerating Packable": "game-packed-auto-turret-t4-accelerating-container",
  "Shotgun Mounted Turret T1 Packable": "game-packed-shotgun-turret-t1-container",
  "Shotgun Mounted Turret T2 Packable": "game-packed-shotgun-turret-t2-container",
  "Shotgun Mounted Turret T3 Packable": "game-packed-shotgun-turret-t3-container",
  "Shotgun Mounted Turret T4 Double Barrel Packable": "game-packed-shotgun-turret-t4-double-barrel-container",
  "Mounted Turret T1 Packable": "game-packed-turret-t1-container",
  "Mounted Turret T2 Packable": "game-packed-turret-t2-container",
  "Mounted Turret T3 Packable": "game-packed-turret-t3-container",
};

/** Family fallback for labels with NO blueprint to key on — prefer routeForBlueprint(),
 *  which is exact. Loot-box labels vary by tier/effort ("Shells Box T1 Mid Effort") but the
 *  wiki models each loot type as ONE untiered container, so match the family prefix → wiki
 *  container slug; each is verified against the store.
 *
 *  These rules are guesses from a display name and have been wrong: "Army Box" pointed at
 *  military-box, the key-locked Military Box, when game_armyBox_* is the Weapon Crate — so
 *  every army box on the map linked to the wrong container. Anything a blueprint can answer
 *  should not be answered here. Ambiguous families (Container Box, Valuable Piles) stay out. */
const FAMILIES: { re: RegExp; slug: string }[] = [
  { re: /^shells box\b/i, slug: "crate-of-shells" },
  { re: /^food box\b/i, slug: "food-crate" },
  { re: /^parts box\b/i, slug: "parts-crate" },
  { re: /^army box\b/i, slug: "weapon-crate" },
  { re: /^medical cabinet\b/i, slug: "medical-cabinet" },
  { re: /^locked box military\b/i, slug: "military-box" },
  { re: /^locked box utility\b/i, slug: "utility-box" },
  { re: /^locked box valuables\b/i, slug: "valuables-box" },
  { re: /^safe\b/i, slug: "valuables-safe" },
  { re: /^valuable pile/i, slug: "coin-crown" }, // ground piles of crowns ("Valuable Piles01"…)
];

/** Lockable door label → the key item that opens it (colour-matched, plus the fort key). */
const DOOR_KEY: Record<string, string> = {
  black: "game-key-island-door-black",
  blue: "game-key-island-door-blue",
  green: "game-key-island-door-green",
  red: "game-key-island-door-red",
  white: "game-key-island-door-white",
  fort: "game-key-island-door-fort",
};

/** Lowercase, trim, collapse internal whitespace. Exported for tests. */
export function __normalize(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}

export interface EntityRoute {
  href: string;
  /** Sprite path (e.g. "/icons/…png") when the entity has one, else null. */
  icon: string | null;
}

/** Resolve a wiki slug to its route + icon, or null if the entity is missing/disabled. */
function routeFor(slug: string): EntityRoute | null {
  const e = getEntity(slug);
  if (!e || e.disabled) return null;
  const base = KIND_ROUTE.find((k) => k.kind === e.kind)?.base;
  return base ? { href: `${base}/${slug}`, icon: e.icon ?? null } : null;
}

let INDEX: Map<string, EntityRoute> | null = null;

/** Build once: normalized-name -> {href}. Higher-priority kinds are inserted
 *  first; lower-priority kinds must not overwrite an existing key. Disabled
 *  entities are skipped — the wiki's hard rule is that disabled entities are
 *  scrubbed from all cross-refs (listByKind does not filter these itself). */
function getIndex(): Map<string, EntityRoute> {
  if (INDEX) return INDEX;
  const m = new Map<string, EntityRoute>();
  for (const { kind, base } of KIND_ROUTE) {
    for (const e of listByKind(kind)) {
      if (e.disabled) continue;
      const key = __normalize(e.name);
      if (!m.has(key)) m.set(key, { href: `${base}/${e.slug}`, icon: e.icon ?? null });
    }
  }
  // curated aliases win over name matches (they correct known mismatches); each is
  // verified against the store so a missing/disabled target is skipped, never dead-linked.
  for (const [label, slug] of Object.entries(ALIASES)) {
    const r = routeFor(slug);
    if (r) m.set(__normalize(label), r);
  }
  INDEX = m;
  return m;
}

/** Route for a loot/container display name, or null if nothing matches. Tries the
 *  built index (exact name + curated aliases) first, then the loot-box family rules. */
export function slugForName(name: string): EntityRoute | null {
  if (!name) return null;
  const hit = getIndex().get(__normalize(name));
  if (hit) return hit;
  for (const f of FAMILIES) if (f.re.test(name.trim())) return routeFor(f.slug);
  return null;
}

/** Route for a container by blueprint id — exact, and the preferred path for anything the
 *  map can identify by blueprint. Display names cannot do this job: "Buried Treasure" is the
 *  wiki's "Suspicious Pile of Sand" (no name match at all), and family guessing sent every
 *  "Army Box" to the key-locked Military Box and "Shells Box T1 Resupply" to the ordinary
 *  Crate of Shells. Falls back to null so callers can try slugForName(). */
export function routeForBlueprint(blueprint: string): EntityRoute | null {
  const hit = (CONTAINER_BLUEPRINTS as Record<string, { slug: string; group: string }>)[blueprint];
  return hit ? routeFor(hit.slug) : null;
}

/** Blueprint first, display name second. Use for anything that names a container. */
export function containerRoute(blueprint: string | undefined, name: string): EntityRoute | null {
  return (blueprint ? routeForBlueprint(blueprint) : null) ?? slugForName(name);
}

export interface LootSetItem {
  name: string; href: string | null; icon: string | null;
  /** Quantity strings as baked, e.g. "300-500". A trailing "~" is never present here —
   *  set rows carry exact per-set amounts, unlike the merged rollup. */
  voyage: string | null; storm: string | null;
}
export interface LootSetView { label: string; chance: number; items: LootSetItem[] }

/** The sets a container can roll, for the map popup.
 *
 *  The baked spawns.json lists a container's loot as one flat "Contents" array — the union
 *  of every set it could roll — which reads as "this is what's inside". It isn't: the game
 *  rolls ONE set and grants that set's items (see LootSetupDataComponent.RollEntry). The
 *  Suspicious Pile of Sand bakes 52 such rows but yields 5-6 items. The wiki's own
 *  role:"loot-set" links carry the truth, so prefer them and fall back to the flat list
 *  when a blueprint isn't a known container.
 *
 *  Keyed on the blueprint id rather than the display label, because labels do not identify
 *  a container: "Buried Treasure" is the wiki's "Suspicious Pile of Sand", and the family
 *  rules send every "Army Box …" to military-box (the locked box) rather than the weapons
 *  crate. The blueprint is the same id the loot pipeline keys on, and it also pins the
 *  exact roll pool — a low-effort crate must not show the high-effort crate's sets.
 *
 *  Returns [] when the blueprint has no set data, so callers keep their existing path. */
export function lootSetsForBlueprint(blueprint: string): LootSetView[] {
  const hit = (CONTAINER_BLUEPRINTS as Record<string, { slug: string; group: string }>)[blueprint];
  if (!hit) return [];
  const e = getEntity(hit.slug);
  if (!e || e.disabled) return [];
  const prefix = `${hit.group} - `;
  const bySet = new Map<string, LootSetView>();
  for (const l of outgoingLinks(hit.slug, ["loot-set"])) {
    if (!l.tier?.startsWith(prefix)) continue;   // another variant's pool
    const key = l.tier;
    let s = bySet.get(key);
    if (!s) {
      s = { label: key.slice(prefix.length), chance: Number(l.value1) || 0, items: [] };
      bySet.set(key, s);
    }
    const target = l.targetSlug ? getEntity(l.targetSlug) : null;
    const base = target && !target.disabled
      ? KIND_ROUTE.find((k) => k.kind === target.kind)?.base
      : undefined;
    s.items.push({
      name: l.name,
      href: base && target ? `${base}/${target.slug}` : null,
      icon: target?.icon ?? null,
      voyage: l.value2, storm: l.value3,
    });
  }
  // Rarest last: the interesting sets are the common ones, and a long tail of 2.4%
  // rows shouldn't push them out of view in a small popup.
  return [...bySet.values()].sort((a, b) => b.chance - a.chance);
}

/** The key a lockable door requires ("Sqr Door Lockable Black" → Black Key), or null.
 *  Doors aren't wiki entities, so this powers a "Requires" row rather than a title link. */
export function doorKey(label: string): { name: string; href: string; icon: string | null } | null {
  const m = /^sqr door lockable (black|blue|green|red|white|fort)\b/i.exec(label || "");
  if (!m) return null;
  const slug = DOOR_KEY[m[1].toLowerCase()];
  const e = getEntity(slug);
  if (!e || e.disabled) return null;
  const base = KIND_ROUTE.find((k) => k.kind === e.kind)?.base;
  return base ? { name: e.name, href: `${base}/${slug}`, icon: e.icon ?? null } : null;
}

/** Reverse backlink for a key: the locations/containers it opens (i.e. the entities
 *  that `requires-key` this key). Empty unless `name` resolves to a game-key-* item. */
export function keyOpens(name: string): { name: string; href: string; icon: string | null }[] {
  const hit = slugForName(name);
  const slug = hit?.href.split("/").pop();
  if (!slug || !/^game-key-/.test(slug)) return [];
  const out: { name: string; href: string; icon: string | null }[] = [];
  for (const l of incomingLinks(slug, ["requires-key"])) {
    const e = getEntity(l.sourceSlug);
    if (!e || e.disabled) continue;
    const base = KIND_ROUTE.find((k) => k.kind === e.kind)?.base;
    if (base) out.push({ name: e.name, href: `${base}/${e.slug}`, icon: e.icon ?? null });
  }
  return out;
}
